# Generated by Django 2.2.4 on 2019-08-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(default='blank', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.ActivityCategory'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Principal'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Activity'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.ObjectCode'),
        ),
    ]
